### ISSUE TITLE
Support cuDNN 7?

### ISSUE THREAD

**Issue by blueberry** [jcuda/jcudnn#2]
@gpu

This is somehow related to https://github.com/jcuda/jcuda/issues/12 I suppose. Any idea about when you will have time and motivation to update jcudnn to cudnn 7?

**Comment by blueberry** [comment]
@gpu

Whooops, I've just seen in the commit history that you've already done that! Thanks!  Then the question is when is it going to be available in maven central :)

**Comment by jcuda** [comment]
It will likely be made available in Maven Central together with the update for CUDA 9. This is discussed in https://github.com/jcuda/jcuda/issues/12 , so I'm closing this issue here for now.
